---
title: Erik Hensarling's Journal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: first.last@gmail.com
description: My journal for anything I feel like writing. Some of it might be useful;
  most of it will be boring.
baseurl: ''
url: https://blog.enh.me
twitter_username: erikhensarling
github_username: eriknh
theme: minima
plugins:
- jekyll-feed
